# Generated by Django 4.1.2 on 2022-11-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postname", models.CharField(max_length=50)),
                ("mainphoto", models.ImageField(blank=True, null=True, upload_to="")),
                ("contents", models.TextField()),
            ],
        ),
    ]
